# -*- coding: utf-8 -*-
"""Natural_Langauge_Process.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g-QZJ-cPjKWgBOQmwRbeEVJ5xJvhr9FQ
"""

!pip install spacy
!python -m spacy download en_core_web_md

class Catogary:
  BOOKS="book"
  CLOTHING="Clothing"

train_x=["i love the book", "this is a great book","the fit is great","i love the shoes"]
train_y=[Catogary.BOOKS,Catogary.BOOKS,Catogary.CLOTHING,Catogary.CLOTHING]



from sklearn.feature_extraction.text import CountVectorizer

vectorizor=CountVectorizer(binary=True);
vector_train_x=vectorizor.fit_transform(train_x);


print(vector.toarray())

from sklearn import svm
clf_svm=svm.SVC(kernel='linear')
clf_svm.fit(vector_train_x,train_y)
vector_train_x=vectorizor.transform(["i love the books"])
clf_svm.predict(vector_train_x)

import spacy

nlp=spacy.load('en_core_web_md')

doc=[nlp(text) for text in train_x]

doc[0]

print(doc)

print(doc[0].vector)

train_x_word_vector=[text.vector  for text in doc]
print(train_x_word_vector)

from sklearn import svm
clf_svm_wv=svm.SVC(kernel='linear')
clf_svm_wv.fit(train_x_word_vector,train_y)
test_x=["i love the hat"]
test_doc=[nlp(text) for text in test_x]
clf_svm_wv.predict([x.vector for x in test_doc])

